### ISSUE TITLE
2. As a Teacher, I want to remove classes if they are no longer necessary.

### ISSUE THREAD

**Issue by VitorCantao** [JambuOverflow/lepic#10]
## Acceptance Criteria

1. If I want to remove a class, I should be able to confirm if I want to remove it.
2. If I remove a class, I should not be able to visualize/use it again.

Sub-Tasks

- [x] Prototype
- [x] Front-End Dev
     - [x] Design 
- [x] Back-End Dev
     - [x] Data Bases

**Comment by TakeshiYoshikawa** [comment]
Essa story está correta, entretanto faltou esse critério "If I want to remove a class, I should be able to confirm if I want to remove it.
". Poderiam verificar isso depois?
