### ISSUE TITLE
5-a. As a user, I want to create an account with a name and role

### ISSUE THREAD

**Issue by VitorCantao** [JambuOverflow/lepic#11]
Roles: (Teacher, Support Professional or Researcher)

## Acceptance Criteria

1. If I created an account, my role and name should remain the same one I put when I signed-up.
2. If I created an account, I should be able to log in with it.
3. If I uninstall the app, I should be able to use my account if I reinstall the app. 
4. When I am signing-up, If I type an incorrect e-mail, It should display a useful error message.
5. It should confirm that my e-mail exists when I am signing-up
6. It should check for weak passwords when I am signing-up

### Front-End 
- [x] Design 
- [x] Front-End Dev
     - [x] Sign-Up
     - [x] Login 

### Back-End
- [x] Data Bases
- [x] POST (Add user)
     - [x] Confirmation e-mail
     - [ ] Error message of confirmation e-mail  
     - [x] E-mail validation
- [x]  Add tests

**Comment by jvcanavarro** [comment]
I think the project wiki is reserved for topics directly related to Lepic like Getting Started, Documentation and FAQ. As I pointed out in that readme it's just a temporary *possible* guideline for developers/contributors during sprints.
