### ISSUE TITLE
10. As a Teacher or Support Professional, I want to create/read/update a text without lenght restriction, so my students/patients can read them.

### ISSUE THREAD

**Issue by VitorCantao** [JambuOverflow/lepic#18]
## Acceptance Criteria

1. If I create a text, the text created should be the same one I typed.
2. I should be able to see the texts added.
3. I should be able to edit a text, and this modification should be saved.

## Sub-Tasks

- [x] Prototype
- [x] Front-End Dev
     - [x] Design 
- [x] Back-End Dev
     - [x] Data Bases

**Comment by TakeshiYoshikawa** [comment]
2000 characters are sufficiently long for a child. Without length is kinda overkill
