### ISSUE TITLE
Study Git

### ISSUE THREAD

**Issue by renan-cunha** [JambuOverflow/lepic#3]
Learn the meaning and application of these git commands https://rogerdudler.github.io/git-guide/index.pt_BR.html

Resource: https://www.atlassian.com/br/git/tutorials/learn-git-with-bitbucket-cloud

Do all the 4 tutorials in "saiba mais sobre o git"

- [x] Isabela
- [x] Takeshi

**Comment by TakeshiYoshikawa** [comment]
Done.
