### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by renan-cunha** [JambuOverflow/lepic#6]
Give priority to questions regarding ADMs, databases and online/offline. Theses questions are architecture related

- [x] Discuss requirements only with developers
- [x] Send Questions
- [x] Read the client answers
    - [x] Make new user stories 
    - [x] Ask new questions (through comments on the docx if the question is related to existing ones, through the forms otherwise) 
- [x] Make diagrams to facilitate requirements understanding (optional)
- [x] Participate in the meetings
- [x] Review user stories

**Comment by aianshay** [comment]
sim mestre

**Comment by aianshay** [comment]
Updated to-do list
