### ISSUE TITLE
1. As a Teacher, I want to create/read/update classes with ids (number, letter or code) and grade (7th grade, 8th grade)

### ISSUE THREAD

**Issue by VitorCantao** [JambuOverflow/lepic#9]
So I can organize the students in groups.

## Acceptance Criteria

1. If I create a class, the grade and id (string) should remain the same ones I put when I created it.
2. If I modify the information of a class, the information in the class data should change.

## Sub-Tasks

- [x] Prototype
- [x] Front-End Dev
     - [x] Design 
- [x] Back-End Dev
     - [x] Data Bases

## Dependency

#11

**Comment by TakeshiYoshikawa** [comment]
O sistema permite inserir uma turma sem o ano (grade) e atualizar para ficar sem também. As turmas continuam listadas, porém aparece "Unexpected Error"
![photo_2021-01-11_20-31-03](https://user-images.githubusercontent.com/29667945/104250324-1e727f80-544c-11eb-895f-8b69f1ed81f0.jpg)
